nixos:
  - changed-files:
      - any-glob-to-any-file:
          - "modules/nixos/**"
          - "hosts/nixos/**"
          - "modules/common/**"

darwin:
  - changed-files:
      - any-glob-to-any-file:
          - "modules/darwin/**"
          - "hosts/darwin/**"
          - "modules/common/**"

home-manager:
  - changed-files:
      - any-glob-to-any-file:
          - "home/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "*.md"
