area:nixos:
  - changed-files:
      - any-glob-to-any-file:
          - "modules/nixos/**"
          - "hosts/nixos/**"

area:darwin:
  - changed-files:
      - any-glob-to-any-file:
          - "modules/darwin/**"
          - "hosts/darwin/**"

area:common:
  - changed-files:
      - any-glob-to-any-file:
          - "modules/common/**"

area:home-manager:
  - changed-files:
      - any-glob-to-any-file:
          - "home/**"

area:docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"

area:ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
          - "Justfile"

area:flake:
  - changed-files:
      - any-glob-to-any-file:
          - "flake.nix"
          - "flake.lock"
          - "helpers/**"
          - "lib/**"
          - "outputs/**"
