{
  lib,
  config,
  ...
}:
let
  cfg = config.desktop'.greetd;
in
{
  options.desktop'.greetd = {
    enable = lib.mkEnableOption "Greetd display manager";
  };

  config = lib.mkIf cfg.enable {
    services = {
      xserver.enable = false; # disable xorg server
      greetd = {
        enable = true;
        settings = rec {
          initial_session = {
            user = config.core'.userName;
            # .wayland-session is a script generated by home-manager, which links to the current wayland compositor(sway/hyprland or others).
            # with such a vendor-no-locking script, we can switch to another wayland compositor without modifying greetd's config here.
            command = "$HOME/.wayland-session"; # start a wayland session directly without a login manager
            # command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd $HOME/.wayland-session";  # start wayland session with a TUI login manager
          };
          default_session = initial_session;
        };
      };
    };
  };
}
